nuget:
  account_feed: true

version: 1.0.0-rc9

before_build:
 - dotnet restore -s https://www.nuget.org/api/v2/
 - cmd: set BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%

build: off

build_script:
 - dotnet build
 
after_build:
 - dotnet test .\Splitio-net-core-tests\Splitio-net-core-tests.csproj
 - dotnet pack .\src\Splitio-net-core --configuration Release

artifacts:
 - path: '**\Splitio-net-core.*.nupkg'
   name: splitio-net-core-nuget

deploy:
 - provider: Environment
   name: NugetNetCorePublish
   on:
    branch: development
